name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  DOTNET_VERSION: "9.0.x"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: edumind_test
          POSTGRES_USER: edumind_test_user
          POSTGRES_PASSWORD: edumind_test_password
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U edumind_test_user -d edumind_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Display .NET info
        run: dotnet --info

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore EduMind.AI.sln

      - name: Build solution
        run: dotnet build EduMind.AI.sln --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: |
          dotnet test tests/AcademicAssessment.Tests.Unit \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage \
            --logger "trx;LogFileName=unit-test-results.trx"

      - name: Run performance tests
        run: |
          dotnet test tests/AcademicAssessment.Tests.Performance \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger "trx;LogFileName=perf-test-results.trx"

      - name: Verify test services are ready
        run: |
          echo "Verifying PostgreSQL is ready..."
          pg_isready -h localhost -p 5432 -U edumind_test_user -d edumind_test

          echo "Verifying Redis is ready..."
          # Test Redis with docker exec instead of redis-cli (not installed by default)
          docker exec $(docker ps -qf "ancestor=redis:7-alpine") redis-cli ping

      - name: Install EF Core tools
        run: dotnet tool install --global dotnet-ef

      - name: Apply database migrations
        run: |
          dotnet ef database update \
            --project src/AcademicAssessment.Infrastructure \
            --startup-project src/AcademicAssessment.Web \
            --context AcademicContext \
            --connection "Host=localhost;Port=5432;Database=edumind_test;Username=edumind_test_user;Password=edumind_test_password"

      - name: Run integration tests
        env:
          LLM__Provider: Stub # Use StubLLMService instead of OLLAMA in CI
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=edumind_test;Username=edumind_test_user;Password=edumind_test_password"
          ConnectionStrings__RedisConnection: "localhost:6379"
          ASPNETCORE_ENVIRONMENT: Testing
        run: |
          dotnet test tests/AcademicAssessment.Tests.Integration \
            --configuration Release \
            --no-build \
            --verbosity normal \
            --logger "trx;LogFileName=integration-test-results.trx" \
            --logger "console;verbosity=detailed"

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: "coverage/**/coverage.cobertura.xml"
          targetdir: "coverage-report"
          reporttypes: "Html;MarkdownSummaryGithub"
          sourcedirs: "src"
          title: "EduMind.AI Code Coverage"

      - name: Add coverage comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: coverage-report/SummaryGithub.md

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage-report
          retention-days: 30

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Tests
          path: "**/*test-results.trx"
          reporter: dotnet-trx
          fail-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: "**/*test-results.trx"
          retention-days: 30

  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore EduMind.AI.sln

      - name: Check formatting
        run: dotnet format EduMind.AI.sln --verify-no-changes --verbosity diagnostic

      - name: Run code analysis
        run: dotnet build EduMind.AI.sln --configuration Release /p:EnforceCodeStyleInBuild=true /p:TreatWarningsAsErrors=false

  build-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire

      - name: Restore dependencies
        run: dotnet restore EduMind.AI.sln

      - name: Build solution
        run: dotnet build EduMind.AI.sln --configuration Release --no-restore

      - name: Run unit tests only (matrix build)
        env:
          LLM__Provider: Stub # Use stub for cross-platform testing
        run: dotnet test tests/AcademicAssessment.Tests.Unit --configuration Release --no-build --verbosity normal
